# -*- coding: utf-8 -*-
"""final_schoolmap - Chidrupee & Aishani.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_zCtiIMh9KtXU016vn6is_kBYA_DU1E
"""

import streamlit as st

st.title("School Map Program")

#nested list of all hallways with the rooms in each
Means_Of_Transportation = [
    ["Cafeteria", "Office", "1", "Front restroom", "Counselor", "Gym", "3","4","5","6","7","8","9","10","11","12"],
    ["Media Center", "16", "Back restroom"],
    ["24","26","27","28","29","30","31","32"],
    ["2", "Commons", "33"],
    ["34","35"],
    ["36","37","38"]
    ]

# Create readable strings of the lists inside the big nested list for the dropdown
dropdown_options = [str(hallway) for hallway in Means_Of_Transportation]

#running the function
start = st.selectbox("Where are you right now?", dropdown_options)
start_l = dropdown_options.index(start)
end = st.selectbox("Where is your destination?", dropdown_options)
end_l = dropdown_options.index(end) # Fixed typo: changed 'start' to 'end'

#adding a dictionary to give directions from each possible starting location to each possible ending location
directions = {
    1: {2: "Walk towards room 12 and turn right", 3: "Walk towards room 12, turn right, and then turn right at the end of the hallway", 4:"Walk towards room 4 and then turn into the hallway next to the gym", 5:"Walk towards room 2 and turn into the hallway by the gym. Then walk past commons area and take first right", 6:"Walk towards room 2 and turn into the hallway by the gym. Then walk past commons area and take second right"},
    2: {1: "Walk towards room 12 and turn left", 3:"Walk towards the restrooms and turn right at the end of the hallway", 4:"Walk towards the restrooms and turn right at the end of the hallway. Then walk towards room 32 and turn right.", 5:"Walk towards the restrooms and turn right at the end of the hallway. Then walk straight past room 32.", 6: "Walk towards the restrooms and turn right at the end of the hallway. Then walk towards room 32 and turn left. Then walk straight and turn right at the end of the hallway."},
    3: {1:"Walk towards room 24, trun left. Then walk past media center and turn left." ,2:"Walk towards room 24, trun left." ,4:"Walk towards room 32 and turn right.",5: "Walk towards room 32 and go straight at the intersection." ,6: "Walk towards room 32, turn left. Then turn right at the end of the hallway." },
    4: {1:"Walk towards room 2 and turn at the intersection." , 2: "Walk in the opposite direction from entrance, turn left. Then walk towards room 24 and turn left." , 3: "Walk in the opposite direction from entrance, turn left.", 5:"Walk in the opposite direction from entrance, take first right. " , 6: "Walk in the opposite direction from entrance, take second right."},
    5: {1: "Walk towards room 34, turn left. Then walk towards room 2 and turn at the intersection." , 2: "Walk stright past room 34 and towards room 24. Then turn left." , 3:"Walk straight past room 34." , 4: "Walk towards room 34, turn left." , 6: "Walk towards room 34, turn right. And then turn right again at the end of the hallway." },
    6: {1: "Walk towards room 36 and turn left. Then walk towards room 2 and turn at the intersection." , 2: "Walk towards room 36 and turn left. Take the left after room 33. Then walk towards room 24 and turn left." , 3: "Walk towards room 36 and turn left. Take the left after room 33.", 4: "Walk towards room 36 and turn left. Walk straight past room 33.", 5:"Walk towards room 36 and turn left. Walk straight and take first left." }
}

#if the hallways of start and end location are the same
if start_l == end_l:
  st.write("You are on the right hallway. The classroom numbers are on the ceiling.")

#if they are different hallway, then use dictionary to print directions
else:
  # Added + 1 to shift 0-5 index up to match your 1-6 dictionary keys
  st.write(directions[start_l + 1][end_l + 1])

