# -*- coding: utf-8 -*-
"""final_schoolmap - Chidrupee & Aishani.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_zCtiIMh9KtXU016vn6is_kBYA_DU1E
"""

import streamlit as st
#nested list of all hallways with the rooms in each
Means_Of_Transportation = [
    ["Cafeteria", "Stage", "Office", "1", "Front restroom", "Counselors", "Gym","2","3","4","5","6","7","8","9","10","11","12"],
    [ "Media Center", "16", "Back restroom"],
    ["24","26","27","28","29","31","30","32","34","35"],
    ["2", "Commons", "Gym", "33"],
    ["36","37","38"]
    ]

#creating a dropdown menu
def dropdown (title, options):
  st.write(f"\n {title}") #print whats in variable "title" on a new line
  #while run_program: #this creates an infinite loop that always runs unless intentionally stopped
    #Print the header
  st.write(title)
    #Print the options using a counter
  number = 1
  for option in options:
    st.write(f"[{number} ] {option}")
    number = number + 1

    #Get the user's choice
  choice_text = st.text_input("Select an option: ")

    #Check the input
  try:
    choice_number = int(choice_text)

    #Check if the number fits inside our list boundaries
    if choice_number >= 1:
      if choice_number <= len(options):
    #Find the item (subtract 1 because lists start at 0)
        index = choice_number - 1
        return options[index]

  except ValueError:
    #This runs if the user typed letters or something else instead of a number
      pass

    # If the code reaches this point, the input was invalid
      st.write("Invalid selection. Please try again.")




#running the function
start = dropdown("Where are you right now? Choose Hallway 1-6", Means_Of_Transportation)
end = dropdown("Where is your destination? Choose Hallway 1-6", Means_Of_Transportation)

#adding a dictionary to give directions from each possible starting location to each possible ending location
directions = {
    1: {2: "Walk towards room 12 and turn right", 3: "Walk towards room 12, turn right, and then turn right at the end of the hallway", 4:"Walk towards room 4 and then turn into the hallway next to the gym", 5:"Walk towards room 2 and turn into the hallway by the gym. Then walk past commons area and take first right", 6:"Walk towards room 2 and turn into the hallway by the gym. Then walk past commons area and take second right"},
    2: {1: "Walk towards room 12 and turn left", 3:"Walk towards the restrooms and turn right at the end of the hallway", 4:"Walk towards the restrooms and turn right at the end of the hallway. Then walk towards room 32 and turn right.", 5:"Walk towards the restrooms and turn right at the end of the hallway. Then walk straight past room 32.", 6: "Walk towards the restrooms and turn right at the end of the hallway. Then walk towards room 32 and turn left. Then walk straight and turn right at the end of the hallway."},
    3: {1:"Walk towards room 24, trun left. Then walk past media center and turn left." ,2:"Walk towards room 24, trun left." ,4:"Walk towards room 32 and turn right.",5: "Walk towards room 32 and go straight at the intersection." ,6: "Walk towards room 32, turn left. Then turn right at the end of the hallway." },
    4: {1:"Walk towards room 2 and turn at the intersection." , 2: "Walk in the opposite direction from entrance, turn left. Then walk towards room 24 and turn left." , 3: "Walk in the opposite direction from entrance, turn left.", 5:"Walk in the opposite direction from entrance, take first right. " , 6: "Walk in the opposite direction from entrance, take second right."},
    5: {1: "Walk towards room 34, turn left. Then walk towards room 2 and turn at the intersection." , 2: "Walk stright past room 34 and towards room 24. Then turn left." , 3:"Walk straight past room 34." , 4: "Walk towards room 34, turn left." , 6: "Walk towards room 34, turn right. And then turn right again at the end of the hallway." },
    6: {1: "Walk towards room 36 and turn left. Then walk towards room 2 and turn at the intersection." , 2: "Walk towards room 36 and turn left. Take the left after room 33. Then walk towards room 24 and turn left." , 3: "Walk towards room 36 and turn left. Take the left after room 33.", 4: "Walk towards room 36 and turn left. Walk straight past room 33.", 5:"Walk towards room 36 and turn left. Walk straight and take first left." }


}

#if the hallways of start and end location are the same
if start == end:
  st.write("You are on the right hallway. The classroom numbers are on the ceiling.")

#if they are different hallway, then use dictionary to print directions
else:
  st.write(directions[start][end])
